name: Build OBIN'SS IA APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Installer Android SDK
        uses: android-actions/setup-android@v3

      - name: Donner les droits à Gradle
        run: chmod +x ./gradlew

      - name: Construire l'APK
        run: ./gradlew assembleDebug

      - name: Publier l'APK
        uses: actions/upload-artifact@v4
        with:
          name: OBINSS-IA-APK
          path: application/build/outputs/apk/debug/*.apk
